# Generated by Django 5.1.13 on 2026-03-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('new_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_new', to='core.faculty')),
                ('new_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_new', to='core.subject')),
                ('original_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_original', to='core.faculty')),
                ('original_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_original', to='core.subject')),
            ],
            options={
                'ordering': ['-date', 'batch', 'time_slot'],
                'unique_together': {('date', 'batch', 'time_slot')},
            },
        ),
    ]
