# Generated by Django 5.1.13 on 2026-03-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_student_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyattendance',
            name='absent_reasons',
            field=models.TextField(blank=True),
        ),
    ]
