# Generated by Django 5.1.13 on 2026-03-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scheduleslot_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
