# Generated by Django 5.1.13 on 2026-03-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_exam_phase_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODWeekLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=10)),
                ('week_index', models.PositiveSmallIntegerField()),
                ('locked_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'verbose_name': 'HOD week lock',
                'verbose_name_plural': 'HOD week locks',
                'ordering': ['department', 'phase', 'week_index'],
                'unique_together': {('department', 'phase', 'week_index')},
            },
        ),
    ]
