# Generated by Django 5.1.13 on 2026-03-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_department_semester_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester label (e.g. Roman IV). Used on Daily Report exports.', max_length=20),
        ),
    ]
