# Generated by Django 5.1.13 on 2026-03-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_department_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='include_extra_lectures_in_attendance',
            field=models.BooleanField(default=False, help_text='If on, extra lectures count in held/percentages like regular slots. If off, faculty can still mark attendance but totals exclude extras.'),
        ),
        migrations.CreateModel(
            name='FacultyDoubtSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_sessions', to='core.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'verbose_name': 'Doubt solving session',
                'verbose_name_plural': 'Doubt solving sessions',
                'ordering': ['-date', '-start_time', '-pk'],
            },
        ),
    ]
