# Generated by Django 5.1.13 on 2026-03-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_faculty_doubt_request_multi_batch_and_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCombineDrCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lecture_slot', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combine_dr_cache_rows', to='core.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combine_dr_cache_rows', to='core.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'verbose_name': 'Faculty DR combine cache row',
                'verbose_name_plural': 'Faculty DR combine cache rows',
                'indexes': [models.Index(fields=['department', 'faculty', 'date'], name='core_facult_departm_8b1b4b_idx')],
                'unique_together': {('faculty', 'date', 'batch', 'lecture_slot')},
            },
        ),
    ]
