# Generated by Django 5.1.13 on 2026-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_faculty_combine_dr_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty_show_doubt_solving',
            field=models.BooleanField(default=True, help_text='If off, faculty sidebar hides Doubt solving and the feature is blocked.'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_show_dr_weekly_load',
            field=models.BooleanField(default=True, help_text='If off, faculty sidebar hides My DR weekly load.'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_show_mark_analytics',
            field=models.BooleanField(default=True, help_text='If off, faculty sidebar hides Mark analytics and related exports.'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_show_marks_report',
            field=models.BooleanField(default=True, help_text='If off, faculty sidebar hides Marks report.'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_show_student_marksheet',
            field=models.BooleanField(default=True, help_text='If off, faculty sidebar hides Student marksheet.'),
        ),
    ]
