# Generated by Django 5.1.13 on 2026-03-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_department_faculty_portal_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycombinedrcache',
            name='effective_load',
            field=models.FloatField(default=0.75, help_text='DR effective load (0.75 default; ETL with present < 24 → 0.5).'),
        ),
    ]
