# Generated by Django 5.1.13 on 2026-03-30 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_attendance_lock_per_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisionExamPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_phases', to='core.department')),
            ],
            options={
                'verbose_name': 'Supervision exam phase',
                'verbose_name_plural': 'Supervision exam phases',
                'ordering': ['department', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SupervisionDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name_raw', models.CharField(blank=True, max_length=250)),
                ('faculty_short_raw', models.CharField(blank=True, max_length=40)),
                ('supervision_date', models.DateField()),
                ('time_slot', models.CharField(blank=True, max_length=120)),
                ('subject_name', models.CharField(blank=True, max_length=200)),
                ('division_code', models.CharField(blank=True, help_text='Stream/classroom assignment from sheet (e.g. SY_1).', max_length=40)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervision_duties', to='core.faculty')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='core.supervisionexamphase')),
            ],
            options={
                'verbose_name': 'Supervision duty',
                'verbose_name_plural': 'Supervision duties',
                'ordering': ['supervision_date', 'time_slot', 'faculty__full_name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentExamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subunit_code', models.CharField(blank=True, help_text='For child accounts only, e.g. SY_1 (must match values in uploaded supervision sheets).', max_length=40)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_coordinator_profiles', to='core.department')),
                ('parent', models.ForeignKey(blank=True, help_text='Null for parent coordinator; set to the SY (parent) profile for SY_1-style accounts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.departmentexamprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_exam_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department exam profile',
                'verbose_name_plural': 'Department exam profiles',
                'constraints': [models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'subunit_code'), name='uniq_exam_subunit_per_parent')],
            },
        ),
    ]
