# Generated by Django 5.1.13 on 2026-03-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_exam_coordination_supervision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentexamprofile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Set by the coordinator on first login (not by exam section). Required before phases or sub-units.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_coordinator_profiles', to='core.department'),
        ),
    ]
