# Generated by Django 5.1.13 on 2026-03-30 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_exam_profile_department_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisionexamphase',
            options={'ordering': ['name'], 'verbose_name': 'Supervision exam phase', 'verbose_name_plural': 'Supervision exam phases'},
        ),
        migrations.AlterUniqueTogether(
            name='supervisionexamphase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='departmentexamprofile',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='If set, this coordinator login was created by a hub account (examsy-style).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_profiles_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisionexamphase',
            name='hub_coordinator',
            field=models.ForeignKey(blank=True, help_text='If set, phase is institute-wide; faculty rows match across all departments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_supervision_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisionexamphase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_phases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisionexamphase',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervision_phases', to='core.department'),
        ),
        migrations.AddConstraint(
            model_name='supervisionexamphase',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('department', 'name'), name='uniq_supervision_phase_per_dept_name'),
        ),
        migrations.AddConstraint(
            model_name='supervisionexamphase',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('hub_coordinator__isnull', False)), fields=('hub_coordinator', 'name'), name='uniq_supervision_phase_per_hub_name'),
        ),
    ]
