# Generated by Django 5.1.13 on 2026-03-30 08:43

from django.db import migrations, models
from django.db.models import Q


def mark_existing_hub_profiles(apps, schema_editor):
    DepartmentExamProfile = apps.get_model('core', 'DepartmentExamProfile')
    DepartmentExamProfile.objects.filter(
        Q(department__isnull=True) & Q(parent__isnull=True)
    ).update(is_hub_coordinator=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_hub_coordinator_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentexamprofile',
            name='is_hub_coordinator',
            field=models.BooleanField(default=False, help_text='If true, no single linked department: manage delegates, sub-units, and institute-wide supervision phases.'),
        ),
        migrations.RunPython(mark_existing_hub_profiles, migrations.RunPython.noop),
    ]
