# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_supervision_duty_completion_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCheckingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_scope', models.BooleanField(default=False, help_text='If true, managed by exam section; faculty matched across all departments.')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='paper_checking_phases_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paper_checking_phases',
                        to='core.department',
                    ),
                ),
                (
                    'hub_coordinator',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='hub_paper_checking_phases',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paper checking phase',
                'verbose_name_plural': 'Paper checking phases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperCheckingDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name_raw', models.CharField(blank=True, max_length=250)),
                ('evaluator_short_raw', models.CharField(blank=True, max_length=40)),
                ('exam_date', models.DateField()),
                ('subject_name', models.CharField(blank=True, max_length=200)),
                ('total_students', models.PositiveIntegerField(default=0)),
                (
                    'deadline_date',
                    models.DateField(help_text='Marks / evaluation target date (default: day after exam date).'),
                ),
                (
                    'faculty',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paper_checking_duties',
                        to='core.faculty',
                    ),
                ),
                (
                    'phase',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='core.papercheckingphase'),
                ),
            ],
            options={
                'verbose_name': 'Paper checking duty',
                'verbose_name_plural': 'Paper checking duties',
                'ordering': ['exam_date', 'subject_name', 'evaluator_short_raw'],
            },
        ),
        migrations.CreateModel(
            name='PaperCheckingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code_raw', models.CharField(max_length=40)),
                ('block_range', models.CharField(blank=True, max_length=160)),
                (
                    'department',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='paper_checking_allocations',
                        to='core.department',
                    ),
                ),
                (
                    'duty',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.papercheckingduty'),
                ),
            ],
            options={
                'verbose_name': 'Paper checking allocation',
                'verbose_name_plural': 'Paper checking allocations',
            },
        ),
        migrations.CreateModel(
            name='PaperSettingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_scope', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='paper_setting_phases_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'department',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paper_setting_phases',
                        to='core.department',
                    ),
                ),
                (
                    'hub_coordinator',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='hub_paper_setting_phases',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paper setting phase',
                'verbose_name_plural': 'Paper setting phases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperSettingDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name_raw', models.CharField(blank=True, max_length=250)),
                ('faculty_short_raw', models.CharField(blank=True, max_length=40)),
                ('duty_date', models.DateField(blank=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                (
                    'faculty',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paper_setting_duties',
                        to='core.faculty',
                    ),
                ),
                (
                    'phase',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='core.papersettingphase'),
                ),
            ],
            options={
                'verbose_name': 'Paper setting duty',
                'verbose_name_plural': 'Paper setting duties',
                'ordering': ['duty_date', 'subject_name', 'faculty_short_raw'],
            },
        ),
        migrations.AddConstraint(
            model_name='papercheckingphase',
            constraint=models.UniqueConstraint(
                condition=models.Q(department__isnull=False, institute_scope=False),
                fields=('department', 'name'),
                name='uniq_paper_check_phase_dept_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='papercheckingphase',
            constraint=models.UniqueConstraint(
                condition=models.Q(hub_coordinator__isnull=False, institute_scope=False),
                fields=('hub_coordinator', 'name'),
                name='uniq_paper_check_phase_hub_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='papercheckingphase',
            constraint=models.UniqueConstraint(
                condition=models.Q(institute_scope=True),
                fields=('name',),
                name='uniq_paper_check_phase_institute_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='papersettingphase',
            constraint=models.UniqueConstraint(
                condition=models.Q(department__isnull=False, institute_scope=False),
                fields=('department', 'name'),
                name='uniq_paper_set_phase_dept_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='papersettingphase',
            constraint=models.UniqueConstraint(
                condition=models.Q(hub_coordinator__isnull=False, institute_scope=False),
                fields=('hub_coordinator', 'name'),
                name='uniq_paper_set_phase_hub_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='papersettingphase',
            constraint=models.UniqueConstraint(
                condition=models.Q(institute_scope=True),
                fields=('name',),
                name='uniq_paper_set_phase_institute_name',
            ),
        ),
    ]
