# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_paper_checking_and_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCheckingCompletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Dismissed')],
                    default='pending',
                    max_length=20,
                )),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                (
                    'decided_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='paper_checking_completion_decisions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'duty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='completion_requests',
                        to='core.papercheckingduty',
                    ),
                ),
                (
                    'faculty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paper_checking_completion_requests',
                        to='core.faculty',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paper checking completion request',
                'verbose_name_plural': 'Paper checking completion requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='papercheckingcompletionrequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(status='pending'),
                fields=('duty', 'faculty'),
                name='uniq_pending_paper_check_completion_per_duty_faculty',
            ),
        ),
    ]
