# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_paper_checking_completion_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCheckingAdjustedShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='paper_check_adjusted_shares_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'duty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='adjusted_shares',
                        to='core.papercheckingduty',
                    ),
                ),
                (
                    'faculty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paper_checking_adjusted_shares',
                        to='core.faculty',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paper checking adjusted share',
                'verbose_name_plural': 'Paper checking adjusted shares',
                'ordering': ['duty_id', 'faculty__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='papercheckingadjustedshare',
            constraint=models.UniqueConstraint(
                fields=('duty', 'faculty'),
                name='uniq_paper_check_adjusted_share_duty_faculty',
            ),
        ),
    ]
