# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_paper_checking_adjusted_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='papercheckingduty',
            name='practical_evaluation_mode',
            field=models.CharField(
                blank=True,
                choices=[('', '—'), ('online', 'Online'), ('offline', 'Offline')],
                help_text='For practical subjects: online vs offline credit rate (set when faculty submits completion).',
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name='PaperCheckingSubjectCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('is_practical', models.BooleanField(
                    default=False,
                    help_text='If true, use online/offline credit rates instead of theory credit.',
                )),
                ('credit_per_paper_theory', models.DecimalField(
                    decimal_places=4,
                    default=0,
                    help_text='Credit per paper for theory subjects (or default when not practical).',
                    max_digits=10,
                )),
                ('credit_online_per_paper', models.DecimalField(decimal_places=4, max_digits=10, null=True, blank=True)),
                ('credit_offline_per_paper', models.DecimalField(decimal_places=4, max_digits=10, null=True, blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'phase',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subject_credits',
                        to='core.papercheckingphase',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Paper checking subject credit',
                'verbose_name_plural': 'Paper checking subject credits',
                'ordering': ['subject_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='papercheckingsubjectcredit',
            constraint=models.UniqueConstraint(
                fields=('phase', 'subject_name'),
                name='uniq_paper_check_subject_credit_phase_subject',
            ),
        ),
    ]
