# Generated by Django 5.1.13 on 2026-04-01 04:43

import django.db.models.deletion
from django.db import migrations, models


def seed_faculty_memberships(apps, schema_editor):
    Faculty = apps.get_model('core', 'Faculty')
    FD = apps.get_model('core', 'FacultyDepartmentMembership')
    for f in Faculty.objects.all().only('id', 'department_id'):
        if f.department_id:
            FD.objects.get_or_create(faculty_id=f.pk, department_id=f.department_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_departmentexamcreditrule_remuneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty_portal_enabled',
            field=models.BooleanField(default=True, help_text='Master switch: when off, this department is hidden from faculty portal (attendance, mentorship, etc.). HOD / super admin dashboards are unchanged.'),
        ),
        migrations.AddField(
            model_name='institutesemester',
            name='faculty_portal_active',
            field=models.BooleanField(default=True, help_text='When off, faculty users cannot see attendance, mentorship, or other portal data for departments in this period. Super admin and departmental admin views are unchanged.'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dr_export_semester_label',
            field=models.CharField(blank=True, help_text='Short label for Daily Report exports (e.g. Roman IV) — not the institute semester record.', max_length=20),
        ),
        migrations.AlterField(
            model_name='departmentexamcreditrule',
            name='remuneration',
            field=models.DecimalField(decimal_places=2, default=0, help_text='₹ per same unit as credit (per duty for setting/supervision; per paper for checking fallback).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='papercheckingduty',
            name='practical_evaluation_mode',
            field=models.CharField(blank=True, choices=[('', '—'), ('online', 'Online'), ('offline', 'Offline')], help_text='Legacy field; practical credits now use online+offline rates × papers in one submission.', max_length=16),
        ),
        migrations.CreateModel(
            name='FacultyDepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_memberships', to='core.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='core.faculty')),
            ],
            options={
                'verbose_name': 'Faculty department membership',
                'verbose_name_plural': 'Faculty department memberships',
                'constraints': [models.UniqueConstraint(fields=('faculty', 'department'), name='uniq_faculty_department_membership')],
            },
        ),
        migrations.RunPython(seed_faculty_memberships, migrations.RunPython.noop),
    ]
