# Generated by Django 5.1.13 on 2026-04-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_faculty_multi_department_portal_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='portal_canonical',
            field=models.ForeignKey(blank=True, help_text='If set, this row is a duplicate person; timetable/attendance for this row is shown when the linked faculty (with login) uses the portal. Set on the non-login row only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_duplicate_rows', to='core.faculty'),
        ),
    ]
