# Generated by Django 5.1.13 on 2026-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_faculty_portal_canonical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty_portal_enabled',
            field=models.BooleanField(default=False, help_text='Master switch: when off, this department is hidden from faculty portal (attendance, mentorship, etc.). HOD / super admin dashboards are unchanged. Enable in Management when this division should use the faculty portal.'),
        ),
        migrations.AlterField(
            model_name='institutesemester',
            name='faculty_portal_active',
            field=models.BooleanField(default=False, help_text='When off, faculty users cannot see attendance, mentorship, or other portal data for departments in this period. Super admin and departmental admin views are unchanged. Turn on when the period is ready for faculty.'),
        ),
    ]
