# Generated by Django 5.1.13 on 2026-04-01 08:39

from django.db import migrations, models


def seed_exam_sidebar_flags_for_existing_departments(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    Department.objects.all().update(
        faculty_show_exam_duties=True,
        faculty_show_exam_credits_analytics=True,
        faculty_show_student_analytics=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_faculty_portal_defaults_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty_show_exam_credits_analytics',
            field=models.BooleanField(default=False, help_text='If off, faculty sidebar hides Exam credits & analytics.'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_show_exam_duties',
            field=models.BooleanField(default=False, help_text='If off, faculty sidebar hides My exam duties and related actions.'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_show_student_analytics',
            field=models.BooleanField(default=False, help_text='If off, faculty sidebar hides Student Analytics.'),
        ),
        migrations.RunPython(seed_exam_sidebar_flags_for_existing_departments, noop_reverse),
    ]
