# Generated by Django 5.1.13 on 2026-04-02 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_departmentexamprofile_user_fk_multi_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutesemester',
            name='faculty_portal_active',
            field=models.BooleanField(default=False, help_text='When off, faculty users cannot see attendance, mentorship, or other portal data for departments in this period. Super admin and departmental admin views are unchanged. Turn on when the period is ready for faculty. Exam duties and credits for this semester still appear under History (read-only) when exam menu is enabled for the department.'),
        ),
        migrations.AlterField(
            model_name='papercheckingphase',
            name='institute_semester',
            field=models.ForeignKey(blank=True, help_text='Empty for exam-section (institute) phases — shared across all academic semesters. Required for department / hub phases.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_checking_phases', to='core.institutesemester'),
        ),
        migrations.AlterField(
            model_name='papersettingphase',
            name='institute_semester',
            field=models.ForeignKey(blank=True, help_text='Empty for exam-section (institute) phases — shared across all academic semesters. Required for department / hub phases.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_setting_phases', to='core.institutesemester'),
        ),
    ]
