# Generated by Django 5.1.13 on 2026-04-03 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_institutesemester_faculty_portal_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papercheckingsubjectcredit',
            name='credit_per_paper_theory',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Legacy field; computation uses institute piecewise formulas (not this value).', max_digits=10),
        ),
        migrations.CreateModel(
            name='RiskStudentMentorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('attendance_week', 'Attendance week'), ('marks_subject', 'Marks subject')], max_length=20)),
                ('phase', models.CharField(help_text='T1–T4 exam/term phase.', max_length=4)),
                ('week_index', models.PositiveSmallIntegerField(blank=True, help_text='0-based week within phase; attendance rows only.', null=True)),
                ('subject_name', models.CharField(blank=True, help_text='Marks rows only: failed subject name.', max_length=200)),
                ('contact_person', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], default='Father', max_length=20)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('call_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_mentor_logs', to='core.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_mentor_logs_saved', to='core.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_mentor_logs', to='core.student')),
            ],
            options={
                'verbose_name': 'Risk student mentor log',
                'verbose_name_plural': 'Risk student mentor logs',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'attendance_week')), fields=('student', 'kind', 'phase', 'week_index'), name='uniq_risk_mentor_log_attendance'), models.UniqueConstraint(condition=models.Q(('kind', 'marks_subject')), fields=('student', 'kind', 'phase', 'subject_name'), name='uniq_risk_mentor_log_marks')],
            },
        ),
    ]
