# Generated by Django 5.1.13 on 2026-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_risk_student_mentor_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty_show_risk_student_info',
            field=models.BooleanField(default=True, help_text='If off, Risk student info (faculty + admin), student-wise Excel, and admin Risk students (Excel) export are hidden and blocked.'),
        ),
    ]
