# Generated by Django 5.1.13 on 2026-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_department_to_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod', 'HOD'), ('faculty', 'Faculty'), ('student', 'Student')], max_length=20),
        ),
    ]
