# Generated by Django 5.1.13 on 2026-03-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_exam_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod', 'HOD'), ('exam_admin', 'Exam Admin'), ('exam_section', 'Exam Section'), ('dept_exam_parent', 'Department exam coordinator (parent)'), ('dept_exam_child', 'Department exam sub-unit (e.g. SY_1)'), ('faculty', 'Faculty'), ('student', 'Student')], max_length=20),
        ),
    ]
