# Generated by Django 5.2.12 on 2026-04-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_exam_coordination_supervision'),
        ('core', '0048_student_user_multi_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.department')),
                ('role_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='accounts.userrole')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role_profile', 'department'), name='uniq_userrole_department_assignment')],
            },
        ),
    ]
