# Generated by Django 5.2.12 on 2026-04-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userrole_department_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoleDepartmentAssignment',
        ),
    ]
